Welcome to TBS

This is a turn based strategy game where all the configuration is <b>completely</b> open! If you would like to get involved and make your own units and maps check out our github:

<a href='https://github.com/James-Silvester/TBSConfig/'>Game Config</a>

This is still very much an <b>ALPHA</b> so please be kind

Much much more content to follow and bugs to fix!

<a href='https://www.turn-based-strategy.co.uk/'>Website/Dev log</a>

Enjoy and feedback/bugs/ideas welcome!

<b>turn.based.strategy.game@gmail.com</b>
